language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: XG6osoMqgAeKqhaQ7DnVmBrSLTGkuh+ofiq5UtmRCvwe6bsAbiUIYQ+VjW4/LIwhl4RH7Zjl9Ox8sa0zFfRxSNwVSROKgPRTPytpFTuUXLeiSy/juF+sXtWemUFpe5Uz2WvyykpggIKMbqCJt9Genck6lKzCv/yqAw4EYy2J+UzuE4kAtyPhJIhdCEOYWTarlN8ItZVkVRDRqRtTlAl9TF7HLflDlpkZoiBjF1bnGYzHVy3EK2Q8K1nNIo2wllcBQHBWc1K1ej3cmXLpjTOQjNkAsMRPh58gbYp0x70RehRK8gCy3lC1/sROL8Wr3LotW+Oidm9vVeAUAVBTQLWzDiJa6EMosBiwD+4L38wNHGTADVmwGXJLhkVhuAi6sIIa7bLafN83P28q4JS2AxWmsAEBTSUtKOXx/awcuoaKDo59iV2nn4enqxrAD1D7VUdviRLSPfEykFWFW7hunL/sS24DH3WjyihodawDYSq2fbloeNuLazMyAEk+Ps62ICYD41fq95KSRhmhiuzHhKD4P4iWndo+NyNBQKfxuRlNlR2fkc0BrvzbKcaZihS2PGj3sBsTjPYcwl+sld59Pvwclj/lKS8F65QuJ+sjW++wo6TqLstTumzrCmNGnTq4LIVOhq2U8v9zM17D6aavDMnpiHZd4U9m3Q6sXYgtb6ZeeVg=
  app: inventory-mgmt-demo
